[build]
  command = "npm run build"
  publish = "build"
[prerender]
  enable = true
[headers]
  Cache-Control = "no-cache, no-store, must-revalidate"
  Pragma = "no-cache"
  Expires = "0"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200